import {outbound,overviewStock,overviewRows,warranty,seriesForRange,number,percent,displayDate,snapshot} from './fixtures.mjs';
const params=new URLSearchParams(location.search);
const module=params.get('module')||'overview', state=params.get('state')||'default';
const $=id=>document.getElementById(id);
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const paths={home:'M3 10 12 3l9 7M5 9v12h14V9M9 21v-8h6v8',box:'m12 3 9 5v9l-9 5-9-5V8l9-5m0 10 9-5M3 8l9 5v9M7.5 5.5l9 5',down:'M12 3v18m-7-7 7 7 7-7',up:'M12 21V3m-7 7 7-7 7 7',file:'M6 2h8l4 4v16H6V2m8 0v5h4M9 11h6M9 15h6M9 19h4',wrench:'M21 3a6 6 0 0 1-8 8L5 20a2 2 0 0 1-3-3l9-8a6 6 0 0 1 8-8l-4 4 3 3 3-5',grid:'M3 3h6v6H3zM15 3h6v6h-6zM3 15h6v6H3zM15 15h6v6h-6z',chart:'M3 21h18M5 17V9h3v8m3 0V4h3v13m3 0v-5h3v5',user:'M8 5a4 4 0 1 0 8 0a4 4 0 1 0-8 0M3 22v-2a9 9 0 0 1 18 0v2',clock:'M12 8v5l4 2M3 12a9 9 0 1 0 18 0a9 9 0 1 0-18 0',search:'M10 3a7 7 0 1 0 0 14a7 7 0 0 0 0-14M15 15l7 7',check:'m5 12 4 4L19 6',warning:'m12 3 10 18H2L12 3M12 9v5m0 3v1',lock:'M7 10V6a5 5 0 0 1 10 0v4M5 10h14v12H5V10m7 4v4',bell:'M5 17h14l-2-4V8a5 5 0 0 0-10 0v5l-2 4m5 3h4',plus:'M12 3v18M3 12h18',download:'M12 2v13m-5-5 5 5 5-5M3 15v6h18v-6',eye:'M1 12s4-7 11-7 11 7 11 7-4 7-11 7S1 12 1 12m8 0a3 3 0 1 0 6 0a3 3 0 1 0-6 0',edit:'m3 17 1 4 4-1L21 7l-4-4L3 17m11-11 4 4',chevron:'m9 5 7 7-7 7',refresh:'M4 6a9 9 0 0 1 16 5M4 1v5h5M20 18a9 9 0 0 1-16-5m16 10v-5h-5',logout:'M10 3H3v18h7M8 12h13m-4-4 4 4-4 4',scan:'M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5M7 7h10v10H7z',calendar:'M3 5h18v17H3V5m4-3v6m10-6v6M3 10h18',more:'M12 4v1m0 6v1m0 6v1',info:'M3 12a9 9 0 1 0 18 0a9 9 0 1 0-18 0m9-1v6m0-11v1'};
const icon=(name)=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.info}"/></svg>`;
const button=(label,{id='',primary=false,disabled=false,kind='',ic=''}={})=>`<button type="button" ${id?`id="${id}"`:''} class="${primary?'primary ':''}${kind}" ${disabled?'disabled':''}>${ic?icon(ic):''}${label}</button>`;
const badge=(label)=>`<span class="badge ${/Hoàn|hoàn|Đã xuất|Đã ghi|hoạt động/.test(label)?'success':/Chờ|Nháp/.test(label)?'warning':/hủy|Quá hạn/.test(label)?'danger':'info'}">${esc(label)}</span>`;
const banner=(text,tone='info',small='')=>`<div class="banner ${tone}" role="status">${icon(tone==='success'?'check':tone==='info'?'info':'warning')}<div><strong>${text}</strong>${small?`<small>${small}</small>`:''}</div></div>`;
const brand=()=>`<div class="brand">${icon('scan')}<span>HOA NAM SCANNER<small>WMS · Vận hành chuyên nghiệp</small></span></div>`;
const warehouse=()=>`<div class="warehouse" aria-label="Kho Hoa Nam, chỉ đọc">${icon('home')}<div><b>Kho Hoa Nam</b><small>● Đang hoạt động</small></div></div>`;
const navItems=[['home','Tổng quan','overview'],['down','Nhập kho','inbound'],['up','Xuất kho','issue'],['box','Quản lý tồn kho','stock'],['wrench','Bảo hành & sửa chữa','warranty'],['grid','Quản lý mã SKU','sku'],['home','Quản lý kho','warehouse'],['chart','Báo cáo','report']];
function shell(content,cls='',active='report'){
return `<aside class="sidebar">${brand()}<div class="nav">${navItems.map(([ic,text,key])=>`<div class="nav-item ${key===active?'active':''}">${icon(ic)}<span>${text}</span></div>`).join('')}</div><div class="nav-caption">HỆ THỐNG</div><div class="nav-item">${icon('user')}<span>Người dùng & phân quyền</span></div><div class="nav-item">${icon('grid')}<span>Cài đặt</span></div><div class="nav-item">${icon('clock')}<span>Nhật ký hoạt động</span></div><div class="side-bottom">Kho Hoa Nam<br>● Đang hoạt động<br><br>© 2026 Hoa Nam</div></aside><div class="shell ${cls}"><header class="topbar"><div class="global-search">${icon('search')}<span>Tìm kiếm SKU, serial, phiếu, sản phẩm…</span></div><div class="user">${icon('bell')}<span class="avatar">NA</span><span>Nguyễn Văn A<small>Quản trị viên</small></span></div></header><main class="workspace">${content}</main></div>`;
}
const pageHead=(title,sub,breadcrumb,actions='')=>`<section class="page-head"><div><div class="breadcrumb">${breadcrumb}</div><h1>${title}</h1><p>${sub}</p></div><div class="head-actions">${actions}${warehouse()}</div></section>`;
function field(label,value='Tất cả',{id='',error=false,readonly=false,large=false,select=false,disabled=false}={}){
return `<div class="field ${error?'error ':''}${readonly?'readonly ':''}${large?'large':''}"><label ${id?`for="${id}"`:''}>${label}</label>${select?`<select ${id?`id="${id}"`:''} ${disabled?'disabled':''}><option>${esc(value)}</option></select>`:`<input ${id?`id="${id}"`:''} value="${esc(value)}" ${readonly?'readonly':''} ${disabled?'disabled':''} ${error?'aria-invalid="true" aria-describedby="date-error"':''}>`}${error?'<small id="date-error">Ngày bắt đầu không được sau ngày kết thúc.</small>':''}</div>`;
}
const kpi=(label,value,sub,ic='box',tone='')=>`<div class="card kpi"><span class="tile-icon ${tone}">${icon(ic)}</span><div>${label}<strong>${value}</strong><small class="${tone}">${sub}</small></div></div>`;
function emptyPanel(title,description='',action='',tone='') {return `<div class="empty-panel ${tone}">${icon(tone==='red'?'warning':'box')}<h2>${title}</h2>${description?`<p>${description}</p>`:''}${action?button(action,{primary:true}):''}</div>`;}
const skeletonRows=(n=5)=>Array.from({length:n},()=>`<div class="skeleton-row">${Array.from({length:5},()=>'<span class="skeleton"></span>').join('')}</div>`).join('');
const pagination=(total)=>`<div class="pagination">${button('‹',{kind:'text'})}${button('1',{kind:'active'})}${button('2',{kind:'text'})}${button('3',{kind:'text'})}<span>…</span>${button(String(total),{kind:'text'})}${button('›',{kind:'text'})}</div>`;
function donut(data,subtitle='Tổng phiếu'){
 const total=data.reduce((s,d)=>s+d.value,0); let offset=0;
 const circles=data.filter(d=>d.value>0).map(d=>{const length=d.value/total*100;const result=`<circle data-segment="${d.key}" data-value="${d.value}" cx="105" cy="105" r="72" pathLength="100" fill="none" stroke="${d.color}" stroke-width="25" stroke-dasharray="${length} ${100-length}" stroke-dashoffset="${-offset}" transform="rotate(-90 105 105)"/>`;offset+=length;return result;}).join('');
 return `<div class="donut-wrap"><svg class="donut" viewBox="0 0 210 210" role="img" aria-label="${esc(data.map(d=>d.label+': '+d.value).join(', '))}"><circle cx="105" cy="105" r="72" fill="none" stroke="#e5edf2" stroke-width="25"/>${circles}<text x="105" y="105" text-anchor="middle" font-size="35" font-weight="700">${number(total)}</text><text x="105" y="132" text-anchor="middle" font-size="12">${subtitle}</text></svg><div class="legend-rows">${data.map(d=>`<div><span><i class="dot" style="background:${d.color}"></i>${d.label}</span><strong>${number(d.value)} <small>${percent(d.value,total)}</small></strong></div>`).join('')}</div></div>`;
}
function chartSVG(series,mode='inventory'){
 const width=820,height=230,left=42,right=mode==='inventory'?58:24,top=18,bottom=36,plotW=width-left-right,plotH=height-top-bottom;
 const count=series.length;const yMax=mode==='inventory'?250:300; const stockMax=800;const step=plotW/count;const barW=Math.min(32,step/(mode==='inventory'?3:1.8));
 const ticks=Array.from({length:5},(_,i)=>{const v=yMax*i/4,y=top+plotH*(1-i/4);return `<path d="M${left} ${y}H${width-right}" stroke="#d6e6ee" stroke-dasharray="3 4"/><text x="${left-8}" y="${y+4}" text-anchor="end">${Math.round(v)}</text>${mode==='inventory'?`<text x="${width-right+10}" y="${y+4}" fill="#9632e8">${stockMax*i/4}</text>`:''}`;}).join('');
 const bars=series.map((p,i)=>{const x=left+step*(i+.5);const cols=mode==='inventory'?[['incoming','#006a94',x-barW-2],['outgoing','#ef8b20',x+2]]:[['value',i===count-1?'#16a8d8':'#006a94',x-barW/2]];return `<g data-chart-day="${p.date}">${cols.map(([key,color,bx])=>`<rect data-series="${key}" data-value="${p[key]}" x="${bx}" y="${top+plotH*(1-p[key]/yMax)}" width="${barW}" height="${plotH*p[key]/yMax}" rx="2" fill="${color}"/>`).join('')}${mode==='outbound'?`<text class="bar-label" x="${x}" y="${top+plotH*(1-p.value/yMax)-9}" text-anchor="middle">${p.value}</text>`:''}<text x="${x}" y="${height-14}" text-anchor="middle" font-size="${count>14?8:11}">${p.date.slice(8)}/${p.date.slice(5,7)}</text></g>`;}).join('');
 const line=mode==='inventory'?`<polyline data-stock-line points="${series.map((p,i)=>`${left+step*(i+.5)},${top+plotH*(1-p.closing/stockMax)}`).join(' ')}" fill="none" stroke="#9632e8" stroke-width="2.5"/>${series.map((p,i)=>`<circle data-stock-day="${p.date}" data-value="${p.closing}" cx="${left+step*(i+.5)}" cy="${top+plotH*(1-p.closing/stockMax)}" r="3" fill="#9632e8"/>`).join('')}`:'';
 return `<svg class="chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="${mode==='inventory'?'Nhập, xuất và tồn cuối ngày':'Sản lượng xuất theo ngày'}">${ticks}${bars}${line}</svg>`;
}
function outboundPage(){
 const st=Number(state.replace('p',''))||1,loading=st===2,empty=st===3,error=st===4,invalid=st===5,noResult=st===6,readonly=st===7,rowFocus=st===8,success=st===9;
 const unavailable=loading||empty||error||invalid||readonly;
 const subtitle=readonly?'Chỉ xem · Bạn vẫn có thể lọc, tìm kiếm và xem chi tiết. Không có quyền xuất báo cáo.':success?'✓ Đã cập nhật báo cáo — Dữ liệu đã được làm mới.':'Theo dõi sản lượng, tiến độ và chứng từ xuất kho';
 let content=pageHead('Báo cáo xuất kho',subtitle,'Báo cáo / Xuất kho',button('Xuất Excel',{id:'export',primary:true,disabled:unavailable,ic:'download'}));
 content+=`<section class="card filters">${field('Khoảng thời gian',invalid?'10/09/2026 – 04/09/2026':'04/09/2026 – 10/09/2026',{id:'range',error:invalid,disabled:loading})}${field('Khách hàng','Tất cả',{select:true,id:'customer',disabled:loading})}${field('Trạng thái','Tất cả',{select:true,id:'status-filter',disabled:loading})}<div class="actions">${button('Áp dụng',{id:'apply',primary:true,disabled:loading||invalid})}${button('Đặt lại',{id:'reset',kind:'text',disabled:loading})}</div></section>`;
 if(invalid)content+=`<div class="fixture">Đang hiển thị kết quả hợp lệ gần nhất: 04/09/2026 – 10/09/2026. Chưa gửi bộ lọc lỗi.</div>`;
 if(error)return shell(content+`<section class="card">${emptyPanel('Không thể tải báo cáo','Đã xảy ra lỗi khi tải dữ liệu. Vui lòng thử lại.','Thử lại','red')}</section>`,'outbound');
 content+=`<section class="kpis">${kpi('Sản phẩm đã xuất',loading?'<span class="skeleton" style="display:block;width:120px"></span>':empty?'0':'1.186',empty?'Không có sản phẩm trong kỳ':loading?'Đang tải dữ liệu':'↑ +18% so với kỳ trước','box')}${kpi('Phiếu đã xuất',loading?'—':empty?'0 / 0':'38 / 42',empty?'Tỷ lệ: —':loading?'Đang tải dữ liệu':percent(38,42)+' tổng phiếu','file')}${kpi('Khách hàng',loading?'—':empty?'0':'24','Có phiếu xuất trong kỳ','user')}${kpi('Phiếu cần xử lý',loading?'—':empty?'0':'4',empty?'Không có phiếu cần xử lý':'2 chờ duyệt · 2 đang đóng hàng','clock','amber')}</section>`;
 content+=`<section class="analytics"><div class="card"><div class="card-heading"><h2>Sản lượng xuất theo ngày</h2><small>Tổng: ${empty?'0':'1.186'} sản phẩm</small></div>${loading?'<div class="skeleton big"></div>':empty?emptyPanel('Chưa có dữ liệu xuất kho'):chartSVG(outbound.daily.map((value,i)=>({value,date:`2026-09-${String(i+4).padStart(2,'0')}`})),'outbound')}</div><div class="card"><h2>Tiến độ phiếu xuất</h2>${loading?'<div class="skeleton big"></div>':donut(outbound.status.map(d=>({...d,value:empty?0:d.value})))}${!empty&&!loading?`<div class="banner warning">${icon('clock')}<b>2 phiếu chờ duyệt</b></div>`:''}</div></section>`;
 content+=`<section class="card"><div class="table-heading"><div class="heading-count"><h2>Danh sách phiếu xuất</h2><span class="count">${empty||noResult?'0':loading?'—':'42'}</span>${rowFocus?'<small>Vừa xem: PX-0042</small>':''}</div><div class="table-search"><input id="table-search" aria-label="Tìm trong danh sách" placeholder="Tìm mã phiếu, khách hàng…" value="${noResult?'PX-9999':''}" ${loading||empty?'disabled':''}></div></div>`;
 if(loading)content+=skeletonRows();else if(empty||noResult)content+=emptyPanel(empty?'Chưa có phiếu xuất':'Không tìm thấy phiếu xuất',empty?'Thử một khoảng thời gian khác.':'Không có phiếu khớp từ khóa đã nhập.',empty?'Điều chỉnh khoảng thời gian':'Xóa tìm kiếm');else content+=`<div class="table-scroll" tabindex="0" aria-label="Danh sách 5 phiếu, cuộn để xem đủ"><table class="outbound-table"><thead><tr>${['Mã phiếu','Ngày xuất','Khách hàng','SL thực xuất','Trạng thái','Người tạo','Chi tiết'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${outbound.rows.map((row,i)=>`<tr class="${rowFocus&&i===0?'recent focused':''}">${row.map((v,j)=>`<td>${j===4?badge(v):j===0?`<b>${v}</b>`:v}</td>`).join('')}<td>${button('Xem',{kind:'text',ic:'chevron'})}</td></tr>`).join('')}</tbody></table></div><div class="table-footer"><span>Trang 1 · 5 / 42 phiếu <span class="tablet-details">Cuộn bảng để xem đủ 5 dòng</span></span>${pagination(9)}</div>`;
 content+=`</section><p class="footnote">Dữ liệu minh họa · 04–10/09/2026 · ${readonly?'Không có quyền xuất báo cáo.':'Kho Hoa Nam'}</p>`;
 return shell(content,'outbound');
}
function warrantyPage(){
 const total=warranty.posted+warranty.draft+warranty.scanning+warranty.cancelled;
 let content=pageHead('Phiếu xuất linh kiện bảo hành','Cấp linh kiện cho hồ sơ bảo hành đang hoạt động','Bảo hành & sửa chữa / Phiếu xuất linh kiện',button('Tạo phiếu xuất linh kiện',{id:'create-warranty',primary:true,ic:'plus'}));
 content+=`<div class="fixture">Chỉ dùng cho bảo hành · Kho Hoa Nam chỉ đọc</div><section class="card summary-panel"><div class="summary-main"><h2>Tổng quan ghi sổ</h2><strong>${warranty.posted} / ${total} <small style="font-size:18px">${percent(warranty.posted,total)}</small></strong><div class="progress"><span style="width:${100*warranty.posted/total}%"></span></div><small>phiếu đã ghi sổ</small></div>${[['Nháp',warranty.draft],['Đang quét/nhập',warranty.scanning],['Đã hủy',warranty.cancelled]].map(([label,n])=>`<div class="summary-stat"><strong>${n}</strong><small>${label}</small></div>`).join('')}</section>${banner('Chỉ phiếu Đã ghi sổ mới làm giảm tồn kho.','info','Nháp, Đang quét/nhập và Đã hủy không làm thay đổi tồn.')}`;
 content+=`<section class="card"><div class="table-heading"><div class="heading-count"><h2>Danh sách phiếu</h2><span class="count">84</span></div><small>Cập nhật mới nhất</small></div><div class="filters" style="margin-bottom:18px">${field('Tìm kiếm','',{id:'warranty-search',large:true})}${field('Trạng thái','Tất cả',{select:true,id:'warranty-status'})}${field('Theo dõi','Tất cả',{select:true,id:'tracking'})}<div class="actions">${button('Áp dụng',{primary:true,id:'apply'})}${button('Đặt lại',{kind:'text',id:'reset'})}</div></div>`;
 content+=`<table class="warranty-table"><thead><tr>${['Phiếu','Hồ sơ bảo hành','Linh kiện','Theo dõi','Trạng thái','Cập nhật','Thao tác'].map(s=>`<th>${s}</th>`).join('')}</tr></thead><tbody>${warranty.rows.map(r=>`<tr><td><strong>${r[0]}</strong><small class="tablet-details">${r[5]}</small></td><td><b>${r[1]}</b><small>${r[2]}</small><small class="tablet-details">${r[3]} · ${r[4]}</small></td><td>${r[3]}<small>${r[4]}</small></td><td>${r[5]}</td><td>${badge(r[6])}</td><td>${r[7]}</td><td><div class="row-action">${button(r[8],{primary:r[8]==='Ghi nhận',ic:r[8]==='Chỉnh sửa'?'edit':r[8]==='Ghi nhận'?'scan':'eye'})}${button('⋮',{kind:'icon-only'})}</div></td></tr>`).join('')}</tbody></table><div class="table-footer"><span>Hiển thị 1–7 / 84 phiếu</span>${pagination(12)}</div></section><p class="footnote">Mục đích phiếu: WARRANTY · Dữ liệu minh họa theo hợp đồng thiết kế v3 · Chưa kết nối API</p>`;
 return shell(content,'warehouse-doc','warranty');
}
function authPage(){
 const states={
 'session-expired':['Phiên đăng nhập đã hết hạn','Vui lòng đăng nhập lại để tiếp tục.','Đăng nhập lại','warning'],
 'access-denied':['Bạn không có quyền truy cập kho này','Vui lòng liên hệ quản trị viên để được hỗ trợ.','Đăng nhập tài khoản khác','danger'],
 'account-unavailable':['Tài khoản hiện không thể tiếp tục truy cập','Vui lòng liên hệ quản trị viên để được hỗ trợ.','Đăng nhập tài khoản khác','danger'],
 'context-load-error':['Không tải được thông tin phiên','Chưa thể xác minh tài khoản và kho. Vui lòng thử lại.','Thử lại','danger'],
 'confirmation-failed':['Không thể xác nhận phiên','Yêu cầu chưa hoàn tất. Vui lòng thử lại.','Thử lại','danger'],
 'offline-before-submit':['Không có kết nối mạng','Kết nối lại để xác nhận phiên đăng nhập.','Kiểm tra kết nối','warning'],
 'outcome-unknown':['Chưa xác định được kết quả','Kết nối bị gián đoạn khi xử lý. Hãy kiểm tra trạng thái trước khi thực hiện lại.','Kiểm tra trạng thái','warning'],
 'warehouse-suspended':['Kho Hoa Nam đang tạm dừng hoạt động','Bạn chưa thể tiếp tục vào kho. Vui lòng liên hệ quản trị viên.','Kiểm tra lại trạng thái','warning']};
 const ready=['default','entering-system','confirmation-failed','warehouse-suspended'].includes(state);
 let card='<h1>Xác nhận phiên đăng nhập</h1>';
 if(ready)card+=`<div class="account" data-identity><span class="avatar">MA</span><div><b>Minh Anh</b><small>Nhân viên kho</small></div></div><div class="warehouse" data-warehouse>${icon('home')}<div><b>Kho Hoa Nam</b><small class="${state==='warehouse-suspended'?'amber':''}">${state==='warehouse-suspended'?'● Tạm dừng hoạt động':'● Đang hoạt động'}</small></div></div>`;
 if(state==='checking-session')card+=`<div aria-busy="true"><div class="skeleton-row"><span class="skeleton"></span></div><div class="skeleton-row"><span class="skeleton"></span></div></div>${banner('Đang kiểm tra phiên đăng nhập…')}${button('Đang kiểm tra…',{disabled:true})}`;
 else if(state==='default'||state==='entering-system')card+=`${banner('Kiểm tra thông tin tài khoản và kho trước khi tiếp tục.')}${button(state==='entering-system'?'Đang vào hệ thống…':'Bắt đầu làm việc',{primary:true,disabled:state==='entering-system',id:'confirm-session',ic:state==='entering-system'?'refresh':''})}${button('Đăng xuất',{kind:'text',disabled:state==='entering-system',ic:'logout'})}`;
 else {const [title,body,cta,tone]=states[state]||states['session-expired'];card+=banner(title,tone,body)+button(cta,{primary:true,id:'auth-primary'});if(state==='confirmation-failed'||state==='warehouse-suspended')card+=button('Đăng xuất',{kind:'text',ic:'logout'});}
 return `<main class="auth"><section class="auth-hero">${brand()}<div><h1>Quản lý kho<br>Hoa Nam</h1><p>Đăng nhập để bắt đầu phiên làm việc</p></div><div class="hero-bottom">CHÍNH XÁC · HIỆU QUẢ · VẬN HÀNH BỀN VỮNG</div></section><section class="auth-area"><div><div class="auth-card" data-state="${state}">${card}</div><footer class="auth-footer">HOA NAM SCANNER<br>KẾT NỐI CON NGƯỜI · VẬN HÀNH HIỆU QUẢ</footer></div></section></main>`;
}
function priorityList(mode='default'){
 return `<div class="priority-list">${[['warning','Sản phẩm sắp hết tồn kho','Có 24 SKU dưới mức tồn tối thiểu',24,'Xem'],['file','Phiếu nhập chờ duyệt','Cần phê duyệt trong hôm nay',4,'Duyệt'],['wrench','Bảo hành quá hạn','Có 4 phiếu quá hạn',4,'Xem'],['clock','Sản phẩm tồn lâu','Có 5 SKU tồn trên 6 tháng',5,'Xem'],['file','Chưa kiểm kê định kỳ','Có 3 khu vực chưa kiểm kê',3,'Lập kế hoạch']].map(([ic,title,sub,count,cta],i)=>`<div class="priority-item ${mode==='urgent'&&i===0?'alert':''}">${icon(ic)}<div><b>${title}</b><small>${sub}</small></div><strong class="${i<3?'red':'amber'}">${count}</strong>${button(cta,{primary:mode==='pending'&&i===1})}</div>`).join('')}</div>`;
}
function picker(invalid=false){
 const from=invalid?'14/09/2026':'04/09/2026';
 return `<div class="overlay"><section class="picker" role="dialog" aria-modal="true" aria-label="Chọn khoảng thời gian"><div><h2>Chọn khoảng thời gian</h2><small>Chỉ áp dụng cho biểu đồ nhập – xuất – tồn kho.</small></div><div class="preset-grid">${['7 ngày gần nhất','14 ngày gần nhất','30 ngày gần nhất','Tùy chỉnh'].map((s,i)=>button(s,{primary:i===3})).join('')}</div><div class="range-fields">${field('Từ ngày',from,{id:'from-date',error:invalid})}${field('Đến ngày','10/09/2026',{id:'to-date',error:false})}</div>${invalid?banner('Ngày bắt đầu phải trước hoặc bằng ngày kết thúc.','danger'):banner('Đang chọn: 04/09/2026 – 10/09/2026 · 7 ngày')}<div><div class="calendar-head"><b>Tháng 9 2026</b><div>${button('‹')}${button('›')}</div></div><div class="week">${['CN','T2','T3','T4','T5','T6','T7'].map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar-grid">${Array.from({length:35},(_,i)=>{const n=i-1;const valid=n>=1&&n<=30;return `<span class="${!valid?'outside':!invalid&&(n===4||n===10)?'endpoint':!invalid&&n>4&&n<10?'in-range':''}">${valid?n:n<1?n+31:n-30}</span>`;}).join('')}</div></div><div class="picker-footer"><span>${invalid?'Khoảng ngày chưa hợp lệ':'04/09/2026 → 10/09/2026 · 7 ngày'}</span><div class="actions">${button('Hủy')}${button('Áp dụng',{primary:true,disabled:invalid,id:'apply-range'})}</div></div></section></div>`;
}
function overviewPage(){
 const filter=module==='filter';const f=filter?Number(state)||1:0;
 const loading=!filter&&state==='loading',empty=!filter&&state==='empty',error=!filter&&state==='error',denied=!filter&&state==='permission-denied';
 const range=f===4?'14d':f===5?'30d':f===8?'custom':'7d',series=seriesForRange(range);
 const chartLoading=loading||f===10,chartEmpty=empty||f===11,chartError=error||f===12,chartDenied=f===13;
 let content=pageHead('Tổng quan','Cùng quản lý kho hiệu quả hơn mỗi ngày.','Hoa Nam / Tổng quan',`<small>${displayDate(snapshot)} · 08:30</small>`);
 if(denied)return shell(content+`<section class="card">${emptyPanel('Bạn chưa có quyền xem Tổng quan','Tài khoản chưa được cấp quyền truy cập màn hình này.','Quay lại')}</section>`,'overview','overview');
 if(error)content+=banner('Không thể tải dữ liệu tổng quan','danger','Đã xảy ra lỗi khi kết nối dữ liệu. Vui lòng thử lại.');
 content+=`<section class="kpis">${[['Tổng tồn kho','647','↑ +12% so với tháng trước','box'],['Giá trị tồn kho','2,8 tỷ','↑ +5% so với tháng trước','file'],['Nhập kho hôm nay','196','↑ +18% so với hôm qua','down'],['Xuất kho hôm nay','56','↓ -8% so với hôm qua','up'],['Việc cần xử lý','12','↓ -25% · nhóm việc','file']].map(([l,v,s,ic])=>kpi(l,loading?'<span class="skeleton" style="display:block;width:95px"></span>':empty?'0':error?'—':v,loading?'Đang tải dữ liệu':empty?'Không có dữ liệu':error?'Chưa tải được dữ liệu':s,ic)).join('')}</section>`;
 const trigger=range==='custom'?'Tùy chỉnh · 05/09–09/09':range==='14d'?'14 ngày gần nhất':range==='30d'?'30 ngày gần nhất':'7 ngày gần nhất';
 let chart=`<div class="card chart-card"><div class="card-heading"><h2>Biểu đồ nhập – xuất – tồn kho</h2>${!chartDenied?button(trigger,{id:'range-trigger',disabled:chartLoading,kind:'range-trigger '+(f===2?'focus-ring':'')}):''}</div><div class="legend"><span><i class="dot" style="background:#006a94"></i>Nhập kho</span><span><i class="dot" style="background:#ef8b20"></i>Xuất kho</span><span><i class="dot" style="background:#9632e8"></i>Tồn cuối ngày</span></div>`;
 if(chartLoading)chart+='<div class="skeleton big" aria-label="Đang tải biểu đồ"></div>';else if(chartError)chart+=emptyPanel('Không tải được dữ liệu biểu đồ','Dữ liệu chưa được xác minh.','Thử lại','red');else if(chartEmpty)chart+=emptyPanel('Chưa có dữ liệu trong khoảng chọn','Chọn một khoảng thời gian khác.','Đặt lại bộ lọc');else if(chartDenied)chart+=emptyPanel('Bạn không có quyền xem biểu đồ','Liên hệ quản trị viên để kiểm tra quyền.');else chart+=chartSVG(series)+`<p class="fixture" data-range-context>Sản phẩm · ${series[0].date.split('-').reverse().join('/')} – ${series.at(-1).date.split('-').reverse().join('/')} · ${series.length} điểm ngày · dữ liệu minh họa</p>`;
 if(f===3)chart+=`<div class="range-menu">${['7 ngày gần nhất','14 ngày gần nhất','30 ngày gần nhất','Tùy chỉnh'].map((x,i)=>button(x,{primary:i===0})).join('')}</div>`;
 if(f===9){const p=series.find(s=>s.date==='2026-09-07');chart+=`<div class="tooltip-card" data-tooltip-date="${p.date}"><b>07/09/2026</b><p>Nhập kho: ${p.incoming}</p><p>Xuất kho: ${p.outgoing}</p><p>Tồn kho: ${p.closing}</p></div>`;}
 chart+='</div>';
 const priority=`<div class="card priority-card"><div class="card-heading"><h2>Công việc cần ưu tiên</h2></div>${loading?skeletonRows(5):empty?emptyPanel('Không có công việc'):error?emptyPanel('Chưa tải được công việc'):priorityList(state)}</div>`;
 content+=`<section class="analytics">${chart}${priority}</section>`;
 let table=`<section class="card"><div class="table-heading"><h2>Phiếu gần đây</h2><small>Xem tất cả →</small></div>`;
 if(loading)table+=skeletonRows(5);else if(empty||error)table+=emptyPanel(empty?'Chưa có phiếu gần đây':'Chưa tải được danh sách');else table+=`<table class="overview-table"><thead><tr>${['Mã phiếu','Loại phiếu','Đối tác/Nhà cung cấp','Số lượng','Trạng thái','Ngày tạo'].map(s=>`<th>${s}</th>`).join('')}</tr></thead><tbody>${overviewRows.map((r,i)=>{const focus=state==='pending'&&i===0||state==='processing'&&i===2||state==='completed'&&i===1||state==='overdue'&&i===3;return `<tr class="${focus?'recent focused':''}">${r.map((v,j)=>`<td>${j===4?badge(v):j===0?`<b>${v}</b>`:v}</td>`).join('')}</tr>`;}).join('')}</tbody></table>`;
 table+='</section>';
 const stock=`<section class="card"><div class="card-heading"><h2>Cơ cấu trạng thái tồn kho</h2></div>${loading?'<div class="skeleton big"></div>':empty||error?emptyPanel(empty?'Chưa có dữ liệu kho':'Chưa tải được dữ liệu kho'):donut(overviewStock,'Tổng tồn')}${!empty&&!error&&!loading?banner('24 SKU sắp hết hàng','warning'):''}</section>`;
 content+=`<section class="lower">${table}<div class="lower-duo"><div class="tablet-details">${priority}</div>${stock}</div></section><section class="quick-row">${[['box','Thông tin kho','3 khu vực · Khu A, B, C'],['chart','Tiến độ xử lý hôm nay','12 nhóm việc · 4 hoàn thành'],['calendar','Lịch nhập/xuất trong ngày','4 phiếu dự kiến']].map(([ic,t,s])=>`<div class="card">${icon(ic)}<div><b>${t}</b><small style="display:block">${loading||error?'Chưa tải được':empty?'Chưa có dữ liệu':s}</small></div></div>`).join('')}</section><p class="fixture">Dữ liệu minh họa v3 · Kho Hoa Nam · Bộ lọc biểu đồ không thay đổi KPI ngoài biểu đồ.</p>`;
 const secondary=`<details class="secondary-details"><summary>Tác vụ kho · Nhật ký hoạt động gần đây · Thông tin bổ sung</summary><div class="secondary-body"><h2>Tác vụ kho</h2><div class="actions">${[['Nhập kho','Nhập hàng và kiểm đếm'],['Xuất kho','Soạn hàng theo phiếu'],['Bảo hành','Tiếp nhận và sửa chữa'],['Quét hoặc nhập mã sản phẩm','QR · Serial · SKU — đích thực thi cần PM xác nhận'],['Kiểm tra mã','Đối chiếu thông tin']].map(([a,b])=>`<div class="card"><b>${a}</b><small style="display:block">${b}</small></div>`).join('')}</div><h2>Nhật ký hoạt động gần đây</h2>${loading?skeletonRows():empty||error?emptyPanel(empty?'Không có hoạt động':'Chưa tải được hoạt động'):`<table><thead><tr><th>Người thực hiện</th><th>Nội dung</th><th>Thời gian</th></tr></thead><tbody>${[['Nguyễn Văn B','Nhập kho 120 sản phẩm (PN-0001)','10/09/2026 08:32'],['Trần Thị C','Xuất kho 56 sản phẩm (PX-0004)','09/09/2026 16:20'],['Lê Minh D','Cập nhật bảo hành BH-001','09/09/2026 14:15'],['Nguyễn Văn A','Kiểm kê khu A — Hoàn thành','08/09/2026 10:30'],['Phạm Thị E','Tạo phiếu xuất kho PX-0003','08/09/2026 09:12']].map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>`}<p class="fixture">Dữ liệu minh họa; không gọi API và không tự thêm quyền/luồng quét.</p></div></details>`;
 content=content.replace('<p class="fixture">Dữ liệu minh họa v3 · Kho Hoa Nam · Bộ lọc biểu đồ không thay đổi KPI ngoài biểu đồ.</p>',secondary);
 let result=shell(content,'overview','overview');if(f===6||f===7)result+=picker(f===7);return result;
}
$('app').innerHTML=module==='auth'?authPage():module==='outbound'?outboundPage():module==='warranty'?warrantyPage():overviewPage();
document.documentElement.dataset.module=module;
document.documentElement.dataset.state=state;
document.documentElement.dataset.ready='true';
document.title=`Hoa Nam · ${module} · ${state} · Bản sửa cần duyệt`;
// Static design fixture. These controls intentionally do not call business APIs.
document.addEventListener('click',event=>{if(event.target.closest('button'))event.preventDefault();});
